### ISSUE TITLE
[Code Generation] Change Query.operationDefinition to return the string with joined query source, fragment sources and variables

### ISSUE THREAD

**Issue by sav007** [apollostack/apollo-android#51]

**Comment by felipecsl** [comment]
I just checked the swift code and it doenst include the fragment and variables in the `operationDefinition`. Maybe we should have a separate field for that?

**Comment by sav007** [comment]
@felipecsl how about remove from `Query` `String operationDefinition()`, `List<String> fragmentDefinitions()`, `Map<String, Object> variableDefinitions()` methods, and introduce one instead `String queryDefinition()` that will return the whole query with fragments and variables?

**Comment by felipecsl** [comment]
sounds like a good idea to me!

**Comment by martijnwalraven** [comment]
@sav007: This isn't immediately relevant, but the reason for keeping those separate in the iOS client was because we may want to combine multiple queries in one requests and only want to include fragment definitions once.

**Comment by sav007** [comment]
@martijnwalraven does GraphQL support execution of multiple operations in one request, I thought even if you pass multiple operations in one request, you must provide as a parameter the name of operation you want to execute. So what the point to send multiple, is there any quick example of use case where it requires?

**Comment by martijnwalraven** [comment]
@sav007: There are proposals for batched operations (see [this blog post](https://dev-blog.apollodata.com/new-features-in-graphql-batch-defer-stream-live-and-subscribe-7585d0c28b07#.ccl64yv7g), and [GraphQL Server](http://dev.apollodata.com/tools/graphql-server/requests.html) supports a simpler form where you pass an array of independent query documents.

So it isn't clear whether keeping fragments separate will be useful for these features, but it seems cleaner, and it avoids including the same literal string multiple times in the generated code.

For the combination of operation definition and variable definitions, I would use `queryDocument`, because that is the term used in the spec. `queryDefinition` is what we call `operationDefinition` here (but that could also be a mutation).

Also, by`variableDefinitions`, do you mean the variable values? Because the variable definitions are part op the `operationDefinition`, and the variables themselves are passed separately (in a transport-specific manner). So you don't want to include these in the query document.

**Comment by sav007** [comment]
@felipecsl again back to square one, we have to introduce retrofit request converter, as the query request is not just plain string, it's json with 2 fields: `query` and `variables`. And `variables` is structure of json objects. Type of variable can be scalar or input type that can have another input types as fields. So we can't just serialize variables to string.

**Comment by martijnwalraven** [comment]
@sav007: To complicate matters further, you probably also want to support custom scalars, or at least design this in a way that they can be added later. With custom scalars, you could for example pass in or receive a Java `Date`, and the type will be responsible for serializing/deserializing from a JSON value (with arbitrary code).

**Comment by sav007** [comment]
@martijnwalraven thanks for feedback, the idea with `queryDefinition` was to prepare the final json request body. But this won't work well as then we have to generate code to serialize variables to json in our models. The easiest way is to have converter at runtime module that `ApolloClient` will use to serialize query to json. Can we agree just for now: we are going to have `Query.operationDefinition():String` (join of query and fragment sources) and `Query.variableDefiniton():Map<String, Object>`?

**Comment by martijnwalraven** [comment]
I would use 'variables' instead of 'variableDefinitions, because the variables are defined in the operation, and this is about providing values.

**Comment by felipecsl** [comment]
Based on @martijnwalraven's statement:
```
It isn't clear whether keeping fragments separate will be useful for these features, but it seems cleaner, and it avoids including the same literal string multiple times in the generated code.
```
@sav007 It sounds like we still need to keep `fragmentDefinitions` as well so we can only send the unique fragments used, right?

**Comment by felipecsl** [comment]
Either way I agree that using a retrofit converter is the way to go

**Comment by sav007** [comment]
@felipecsl @martijnwalraven as I understood the batched operations feature is still in progress and not officially supported by GraphQL. So lets wait until it will be released and add support this on our end later
