### ISSUE TITLE
[Runtime] Mapping json response to generated data models

### ISSUE THREAD

**Issue by sav007** [apollostack/apollo-android#55]
Query data model generated by apollo android plugin is represented by interfaces. In order to deserialize query response (json) and map it to the data model, apollo service requires to know about the user defined instance classes of that data model. Generated interface declares only accessor api calls to fields (no setters and of course no fields).

Questions:
1. As we discussed before, custom retrofit converter will be implemented in order to support deserializing response. How this converter will get knowledge about setters / fields of user defined data model implementations to be able to map json response fields? 

2. How converter is going to instantiate the user defined instances of the model interfaces? 

One approach that we considered user uses `AutoValue` lib to generate instances of data model interfaces. Here is an example of generated model interface:

```
public interface Data extends Query.Data {
     Hero hero();

    interface Hero {
       String name();

       AsHuman asHuman();

      interface AsHuman {
         String name();

         List<Friend> friends();

         Float height();

        interface Friend {
           String name();

           List<Episode> appearsIn();
        }
      }
...
```

Then from user to use AutoValue requires to define abstract classes / interfaces that extend all interfaces: `Data`, `Data.Hero`, `Data.Hero.AsHuman`, `Data.Hero.AsHuman.Friend` etc. with `@AutoValue` annotation that seems too overwhelming . Even more `AutoValue` generates immutable `value objects` that initialize fields inside constructor. So retrofit converter has to parse response json and pass parsed field values as parameters to this constructor.
But converter doesn't know anything about user defined instance classes and especially about how to construct them, so it will require some sort of `factory` the same approach as `SQLDelight` implements.

All this complication brings to question, maybe we have to change our code generation to have model be classes with fields, rather then interfaces.

@felipecsl @martijnwalraven @marwanad

**Comment by martijnwalraven** [comment]
I don't know much about best practices on Android, and I got the feeling people value flexibility, but I think there is a lot of benefit in keeping things simple and have them work by default. So generating classes instead of interfaces sounds like a  good strategy to me.

I still don't fully understand how we can use Retrofit converters to read either from cache or from a response (while normalizing the result to the cache it at the same time). The difficulty is that the same code would have to read either from the response name or from a cache key based on field name + arguments. I think the `GraphQLResultReader` approach in Apollo iOS is pretty elegant, so I'd prefer to do something similar in Android.

On iOS, every generated class has a constructor that knows how to initialize a model object from a reader:

```swift
  public init(reader: GraphQLResultReader) throws {
    r2 = try reader.optionalValue(for: Field(responseName: "r2", fieldName: "hero"))
    luke = try reader.optionalValue(for: Field(responseName: "luke", fieldName: "hero", arguments: ["episode": "EMPIRE"]))
  }
```

And the reader is what knows where to get these values from and how to convert them to the right type. Is that something we could somehow get Retrofit to do as well?

**Comment by marwanad** [comment]
> So retrofit converter has to parse response json and pass parsed field values as parameters to this constructor. 

We can use [AutoValueGsonTypeAdapterFactory](https://github.com/rharter/auto-value-gson/blob/master/auto-value-gson/src/main/java/com/ryanharter/auto/value/gson/GsonTypeAdapterFactory.java) and a add a custom GsonConverterFactory to Retrofit to simplify this step. So, there would be no need for a custom converter (?). We still need to be aware of the user implemented classes however.

Is generating auto value classes from the beginning not a possible thing? (I haven't used AutoValue much so I'm not sure about its limitations).

**Comment by sav007** [comment]
@marwanad well yes we can use this adapter, but still user requires to create extensions of all generated interfaces with `@AutoValue` annotation

**Comment by sav007** [comment]
I'm more and more considering  iOS approach is simpler and maybe we should do the same?

**Comment by sav007** [comment]
@marwanad And another problem is that the structure of generated models is slightly different with shape of response, so we can't have just 1:1 mapping

**Comment by sav007** [comment]
Parsing with moshi / gson becomes even more complicated when query and fragment declares the same fields:

Query:
```
...
        node {
          handle
          bodyHtml
          id
          ... Collect
        }
....

fragment Collect on Collection {
  id
  handle
  bodyHtml
  title
  updatedAt
}
```

Response:
```
"node": {
              "id": "gid://shopify/Collection/58026",
              "bodyHtml": "",
              "handle": "snowboards",
              "title": "Snowboards",
              "updatedAt": "2016-06-22T19:40:46Z"
            }
```

Model:
```
...
interface Node {
  String handle()
  String bodyHtml()
  String id()

  Fragments fragments()
  
  interface Fragments {
     Collect collect()
  }
}
```

**Comment by martijnwalraven** [comment]
@sav007: I agree, it seems simpler to me to use a design similar to the iOS approach and avoid additional dependencies. That way, we can get the exact logic we want in the most efficient way.

We should be able to create a `GraphQLResultReader` that wraps a `JSONReader`. (Moshi seems to include a more efficient version of `JSONReader` that uses Okio, so if we also use OkHttp that may make the most sense.) `GraphQLResultReader` could then cache field values so we only parse them once if they are used multiple times (as in the example above).

I think this is also the easiest way to interleave parsing and caching, because `GraphQLResultReader` can build up records as we parse objects, and then publish them to the store once we are done.

Is there still a need for Retrofit with this approach, or could we just use OkHttp directly?

**Comment by sav007** [comment]
Well Retrofit will be nice to use for it's flexibility of plugins / converters, and in case custom converter it passes `okhttp3.ResponseBody` as a parameter, so basically we will work with Okio, the same way how `moshi` converter works:

```
@Override public T convert(ResponseBody value) throws IOException {
    BufferedSource source = value.source();
    try {
      // Moshi has no document-level API so the responsibility of BOM skipping falls to whatever
      // is delegating to it. Since it's a UTF-8-only library as well we only honor the UTF-8 BOM.
      if (source.rangeEquals(0, UTF8_BOM)) {
        source.skip(UTF8_BOM.size());
      }
      return PARSE JSON HERE (source);
    } finally {
      value.close();
    }
  }
```

And with retrofit we can utilize flexibility of call adapters, so if user wants Rx support then he should just add `RxJava Adapter` retrofit call adapter.

**Comment by sav007** [comment]
@felipecsl any thoughts?

**Comment by sav007** [comment]
I took a look at https://github.com/square/moshi/blob/master/moshi/src/main/java/com/squareup/moshi/ClassJsonAdapter.java we can work with this class, turn it into our custom adapter. We will require to make changes to lines: 162 - 172

```
if (index != -1) {
          fieldBinding = fieldsArray[index];
        } else {
          String name = reader.nextName();
          fieldBinding = fieldsMap.get(name);
          if (fieldBinding == null) {
            reader.skipValue();
            continue;
          }
        }
        fieldBinding.read(reader, result);
```

Here we need to handle correctly if current result class (`result` variable) contains `fragments` field, then parsed json value can belong to both, to result class and to appropriate fragment.

**Comment by felipecsl** [comment]
I'm looking into this right now. Will update with my findings

**Comment by sav007** [comment]
Discussion continues with issue #66

**Comment by sav007** [comment]
From discussion we agreed on to not use moshi (as it uses reflection) and create own parser based on JSONReader. Closing.
