### ISSUE TITLE
[Runtime] Add custom moshi JsonAdapter to parse graphql response data with fragments support

### ISSUE THREAD

**Issue by sav007** [apollostack/apollo-android#66]
Response for query with fragments has different shape than generated model classes.
Custom moshi JsonAdapter should be implemented in order to support parsing response for queries with fragments

**Comment by sav007** [comment]
One idea is in my mind to create custom version of `com.squareup.moshi.ClassJsonAdapter`. Correctly implement `com.squareup.moshi.ClassJsonAdapter#fromJson` to not skip json values (line: 166):

```
fieldBinding = fieldsMap.get(name);
          if (fieldBinding == null) {
            reader.skipValue();
            continue;
          }
```

 but check if the model has declared fragments and handle this correctly

**Comment by sav007** [comment]
Or even better if you take a look at source code of that adapter, you will find field bindings. So we add own field binding that will look to both model level fields and fragment fields

**Comment by felipecsl** [comment]
that sounds like a good idea and starting point. Thanks for the investigation!

**Comment by martijnwalraven** [comment]
What is the benefit of building on `ClassJsonAdapter`? If we generate the model classes, we don't need to rely on reflection. And reflection won't give us all the information we need anyway, because the name of the Java field is not enough to be able to read both from the response and from the cache.

It seems to me we're overcomplicating this and it would be much easier (and probably more performant) to use a `GraphQLResultReader-`wrapped `JSONReader` directly from the generated classes.

**Comment by sav007** [comment]
@martijnwalraven @felipecsl 
>because the name of the Java field is not enough to be able to read both from the response and from the cache.

What other information than `__typeName` will be required to read from response and cache?

I found one article about the performance of reflection on Android: http://blog.nimbledroid.com/2016/02/23/slow-Android-reflection.html

Approach using moshi `ClassJsonAdapter` is much easier to go with (from implementation perspective)

With approach using `GraphQLResultReader `  and let models to construct themselves will require:
1. Change our model generation from interface to POJO
2. `JSONReader ` is stream not a dictionary so we cant have structure like iOS does:
```swift
name = try reader.value(for: Field(responseName: "name"))
          height = try reader.optionalValue(for: Field(responseName: "height"))
```
The parsing will be driven by reading tokens from stream an assign values to fields, smth like:
```java
String name = reader.nextName();
if (name.eqauls("name")) {
  name = reader.stringValue()
}
...
```

**Comment by martijnwalraven** [comment]
> What other information than __typeName will be required to read from response and cache?

Among other things, the cache key for a record depends on the field name (not the response name, which is what the Java field name is based on) + arguments (which may also depend on the value of variables, which we don't know until runtime).

So given this query for example:

```graphql
query HeroName($episode: Episode) {
  favorite: hero(episode: $episode) {
    name
  }
}
```

The response will be something like:
```json
{
  "data": {
    "favorite": {
      "name": "R2-D2"
    }
  }
}
```

And the generated model class will be something like:
```java
interface Data {
  Favorite getFavorite();

  interface Favorite {
    String getName();
  }
}
```
 
The cache key for `{ "name": "R2-D2" }` is not `favorite` but `hero(episode:JEDI)` (or some other value for the `$episode` variable), which we can't know if all we have is the response and the model class. So we do need information about the operation and its definition at runtime.

The solution I've converged on in iOS is to make the model class constructor responsible, because that means we don't need to keep and walk another representation, and the resulting code seems clean and very flexible (because the actual behavior is the responsibility of `GraphQLResultReader` and the resolver function it is configured with).

If we don't want to go that way on Android, we'll need some other runtime representation of the operation definition, and appropriate abstractions for the differences in behavior when reading from a response or the normalized cache.

(See [the design doc](https://github.com/apollostack/apollo-android/blob/design-doc/DESIGN.md#runtime-knowledge-of-query-structure) for more details.)

**Comment by martijnwalraven** [comment]
> `JSONReader` is stream not a dictionary so we cant have structure like iOS does

We won't be able to use the exact same API for `GraphQLResultReader`, but I think we can still find a way to make this into a clean API. For example, maybe we could collect the names first from the model class and fragments, and then use those to drive the parsing.

**Comment by sav007** [comment]
From discussion we agreed on to not use moshi (as it uses reflection) and create own parser based on JSONReader. Closing.

**Comment by felipecsl** [comment]
You mean `android.util.JsonReader` right?

**Comment by sav007** [comment]
Yep
