### ISSUE TITLE
Rename packages from com.apollostack to com.apollodata

### ISSUE THREAD

**Issue by felipecsl** [apollostack/apollo-android#87]

**Comment by martijnwalraven** [comment]
@felipecsl: Hey sorry, I talked about this internally, and it turns out we're planning on using apollographql for all our open source stuff and reserve apollodata for the commercial services. We already use the Twitter handle and we'll also be renaming the GitHub organization to apollographql.

So I'm afraid I'll have to ask the Sonatype people to change the group ID as well.

**Comment by martijnwalraven** [comment]
@felipecsl: I think we should be all set! https://issues.sonatype.org/browse/OSSRH-27585

**Comment by sav007** [comment]
@martijnwalraven @felipecsl so the final package name is `com.apollographql` right?

Then we need to rename:
- `com.apollostack.api.graphql` -> `com.apollographql.api`
- `com.apollostack.compiler` -> `com.apollographql.compiler` 
- `com.apollostack.converter.pojo` -> `com.apollographql.converter.pojo` ???
- `com.apollostack.android` (in apollo-converter/moshi module) -> `com.apollographql.converter.moshi` ???
- `com.apollostack.android.gradle` -> `com.apollographql.android.gradle`
- `com.apollostack.android` (in apollo-runtime) -> `com.apollographql.android`
- `com.example.apollostack.sample` -> `com.apollographql.android.sample` ???

**Comment by martijnwalraven** [comment]
@sav007: Yes, or maybe prefix everything with `com.apollographql.android` (so `com.apollographql.android.api` for example)?

**Comment by felipecsl** [comment]
Either way sounds good. Thanks for the update Martijn. I'll proceed with the rename after the current open PRs have been merged

**Comment by sav007** [comment]
@felipecsl you are good to go with renaming packages all PRs merged

**Comment by felipecsl** [comment]
ok working on this now
